import { FormField } from '@/types/formField';

export const galleryFields: FormField[] = [
  {
    id: 'src',
    type: 'file',
    label: 'Image URL',
    placeholder: 'Enter image URL or select file',
    required: true,
    accept: '.jpg,.jpeg,.png,.gif,.webp',
    name: 'image_url',
  },
  {
    id: 'title',
    type: 'input',
    label: 'Title',
    placeholder: 'Enter title',
    required: true,
  },
  {
    id: 'category',
    type: 'select',
    label: 'Category',
    placeholder: 'Enter category (e.g., Spiritual)',
    required: true,
    options: [
      { value: 'all', label: 'All Categories' },
      { value: 'festivals', label: 'Festivals' },
      { value: 'rituals', label: 'Rituals' },
      { value: 'temple', label: 'Temple' },
      { value: 'community', label: 'Community' },
    ],
  },
  {
    id: 'description',
    type: 'textarea',
    label: 'Description',
    placeholder: 'Enter description',
    required: false,
    row: 5,
  },
];

export const eventFields: FormField[] = [
  {
    id: 'title',
    type: 'input',
    label: 'Title',
    placeholder: 'Enter event title',
    required: true,
    className: '',
  },
  {
    id: 'type',
    type: 'select',
    label: 'Event Type',
    placeholder: 'Select event type',
    required: true,
    options: [
      { value: 'festival', label: 'Festival' },
      { value: 'ritual', label: 'Ritual' },
      { value: 'ceremony', label: 'Ceremony' },
      { value: 'community', label: 'Community Gathering' },
      { value: 'temple', label: 'Temple Event' },
    ],
    className: 'space-y-2',
  },
  {
    id: 'date',
    type: 'date',
    label: 'Event Date',
    placeholder: 'Select event date',
    required: true,
  },
  {
    id: 'time',
    type: 'time',
    label: 'Event Time',
    placeholder: 'Select event time',
    required: true,
  },
  {
    id: 'location',
    type: 'input',
    label: 'Location',
    placeholder: 'Enter event location',
    required: true,
  },
  {
    id: 'participants',
    type: 'input',
    label: 'participants',
    placeholder: 'Enter expected participants',
    required: true,
  },
  {
    id: 'description',
    type: 'textarea',
    label: 'Description',
    placeholder: 'Enter detailed description',
    required: true,
    row: 5,
  },
  {
    id: 'src',
    type: 'file',
    label: 'Event Image',
    placeholder: 'Upload event image or select from files',
    required: true,
    accept: '.jpg,.jpeg,.png,.webp',
    name: 'image_url',
  },
  {
    id: 'status',
    type: 'select',
    label: 'Event Status',
    placeholder: 'Select event type',
    required: true,
    options: [
      { value: 'pending', label: 'Pending' },
      { value: 'active', label: 'Active' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
      { value: 'upcoming', label: 'Upcoming' },
    ],
    className: '',
  },
];
